# Generated by Django 5.2.3 on 2025-07-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=50, verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='user',
            name='faculty',
            field=models.CharField(blank=True, choices=[('science', 'Faculty of Science'), ('engineering', 'Faculty of Engineering'), ('social', 'Faculty of Social Sciences'), ('business', 'Faculty of Business'), ('education', 'Faculty of Education')], max_length=50, verbose_name='Faculty'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Designates administrative privileges (different from staff status)', verbose_name='Admin status'),
        ),
    ]
