# Generated by Django 5.2.3 on 2025-07-06 08:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_department_user_faculty_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='faculty',
            field=models.CharField(blank=True, choices=[('science', 'Faculty of Science'), ('engineering', 'Faculty of Engineering'), ('social', 'Faculty of Social Sciences'), ('business', 'Faculty of Business'), ('education', 'Faculty of Education'), ('arts', 'Faculty of Arts'), ('law', 'Faculty of Law'), ('medicine', 'Faculty of Medicine'), ('agriculture', 'Faculty of Agriculture')], max_length=50, verbose_name='Faculty'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Format: +999999999 or 999-999-9999', max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be valid format', regex='^\\+?[\\d\\s\\-\\(\\)]{9,20}$')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, help_text='6-20 character student identification', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Student ID must be 6-20 characters (letters and numbers)', regex='^[A-Z0-9]{6,20}$')], verbose_name='Student ID'),
        ),
    ]
